ARG BASE_IMAGE=choreonoid_robot_assembler_plugin:20.04
FROM ${BASE_IMAGE}

LABEL maintainer "IRSL-tut (https://github.com/IRSL-tut) <faculty@irsl.eiiris.tut.ac.jp>"

SHELL ["/bin/bash", "-c"]

ARG REPO_NAME=test
COPY ${REPO_NAME} /choreonoid_src/choreonoid/ext/robot_assembler_plugin/config/${REPO_NAME}

RUN (cd /choreonoid_src/choreonoid/ext/robot_assembler_plugin/config/${REPO_NAME}/test; mkdir build; cd build; cmake ..; make)
